.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/docs-repair.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/ISSUE_TEMPLATE/rabbit.md
**Issue:**
close #1 
- Criados os templates `rabbit`, `bug-report`, `feature-request`, `docs-repair`
- Adicionadas as tags automáticas por meio dos templates
=> github(issue): definição dos templates

.github/ISSUE_TEMPLATE/tasks.md
**Issue:**
close #6 
- Criado o template `tasks.md`
- Adicionada a tag automática de `task` por meio do template
=> github(issue): cria o template para tasks gerais

.github/workflows/docs.yml, .gitignore, docs/contributing.md, docs/index.md, docs/sprints/sprint-0.md, docs/sprints/sprint-template.md, mkdocs.yml
**Issue:**
close #9 
- Inicializada a documentação
- Criado o arquivo de configuração `mkdocs.yml` para o mkdocs
- Descrição da Sprint 0
- Criação da página de como contribuir
=> docs(mkdocs): inicializa a primeira versão da documentção

docs/sprints/sprint-1.md, mkdocs.yml
- Criação do arquivo `sprint-1.md`
- Descrição dos objetivos da Sprint 1
- Relatório com a ata das reuniões da Sprint
- Exposição de como a Sprint foi finalizada
- Aprovação do tema do projeto pela @RochaCarla
=> docs(mkdocs): relatório dos objetivos da sprint 1

README.md
**Issue:**
close #21 
- Foi criado o básico do README.md para descrever o projeto e explicar como inicializa-lo na sua máquina local
=> docs(readme): descreve o projeto e como inicializa

README.md
**Issue:**
close #27 
Foi corrigido a tradução e adicionado a melhoria na semântica do README.
=> docs(readme): corrige documentação README

docs/sprints/sprint-2.md, mkdocs.yml
- Criado a arquivo `sprint-2.md`
- Ata da reunião de fechamento da _Sprint 2_
- Pedido de aprovação para instação do app Codecov no repositório do projeto
=> docs(sprint): relatório de descrição da sprint 2

docs/sprints/sprint-3.md
- Foi ajustado o número da sprint na documentação do projeto
=> bug(sprint): ajusta o número da sprint na docs

.gitignore, scripts/env.sh
- Foi adicionado o arquivo `.gitignore` para o projeto Django
- Atualizado o `scripts/env.sh` para gerar a chave do Django somente com Python3 sem libs.
=> git(ignore): readiciona o gitignore para o django files

README.md
- Corrige erro de escrita na mensagem para clicar na documentação
=> docs(README): atualiza parte de documentação

docs/sprints/sprint-4.md, mkdocs.yml
- Criado a arquivo `sprint-4.md`
- Ata da reunião de fechamento da _Sprint 4_
- Pedido do token para configuração do app Codecov no repositório do projeto
=> docs(mkdocs): criação da documentação da sprint 4

docs/sprints/sprint-4.md, docs/sprints/sprint-5.md, mkdocs.yml
- Criado a arquivo `sprint-5.md`
- Ata da reunião de fechamento da _Sprint 5_
- Atualiza modo de highlight do texto na _Sprint 4_
=> docs(mkdocs): adicona documentação da sprint 4

docs/sprints/sprint-3.md
- Foi trocado o modo de definir highlights de `*` para `_`
- Além disso foi descrita a troca das tecnologias do projeto que ocorreu na sprint 3
=> docs(mkdocs): nova arquitetura definida na sprint 3

docs/sprints/sprint-6.md, mkdocs.yml
- Criado a arquivo `sprint-6.md`
- Ata da reunião de fechamento da *Sprint 6*
=> task(docs): documentação da sprint 6

README.md, api/entrypoint.sh, docker-compose.yml, docker/Dockerfile, docker/Dockerfile.web, web/package-lock.json
- O arquivo `entrypoint.sh` foi mudado da pasta `/docker` para `/api`
- O `collectstatic` foi retirado do ambiente de desenvolvimento
- Os arquivos de `Dockerfile` e `docker-compose.yml` foram modificados para que os volumes funcionem para o live reload
- No `README.md` foram adicionados os novos passos para execução do projeto
- O arquivo `web/package-lock.json` foi gerado e adicionado
=> fix(docker): arruma os volumes para possibilitar live reload no projeto

.github/workflows/docs.yml, .github/workflows/test.yml
**Issue:**
close #22 
- Organizado o arquivo `docs.yml`
- Cria e configura o fluxo de testes automatizados no arquivo `test.yml`
=> devops(workflows): configura o github action para testes automatizados

api/users/tests.py
**Issue:**
close #69 
- Documentação dos testes do app `users`
- Register
- Login
=> docs(test): descreve cada teste feito no app users

api/api/management/commands/updatedb.py, api/utils/web_scraping.py
- Foram adicionados opções de linha de comando para: 
- Atualizar apenas o semestre desejado
- Deletar os semestres desejados
- Colorização de terminal adicionada, porém requer revisão de configurações do Django
- Formatação de código para os padrões AutoPep8
- Correção/Adição de tipo de retorno de algumas funções.
=> Task/Improve of  updatedb functionalities

api/api/tests.py, api/utils/management/commands/updatemock.py, api/utils/mock/empty.html, api/utils/mock/infos.json, api/utils/mock/just_table.html, api/utils/mock/sigaa.html, api/utils/sessions.py, api/utils/tests.py, api/utils/urls.py, api/utils/views.py, api/utils/web_scraping.py
**Issue:**
close #66 
- Implementados os testes para o web scraping
- Testes para os sessions retrieve
- Verificação das funções utils
- Comando de atualizar os arquivos de mock
=> test(scraping): verifica os casos válidos e inválidos do web scraping e session retrieve

docs/sprints/sprint-7.md, docs/sprints/sprint-8.md, mkdocs.yml
- Adicionado as sprints 7 e 8 na documentação do projeto
=> docs(sprint): Adição das sprints 7 e 8

api/users/backends/google.py
**O que foi corrigido?**
- O Google OAuth retorna `picture` no seu json não `picture_url`
=> fix(users): corrige erro de cadastro da foto do usuário

api/users/urls.py, api/users/views.py, web/app/contexts/UserContext.tsx, web/app/schedules/profile/page.tsx, web/app/utils/api/logout.ts, web/app/utils/settings.ts
=> frontend(logout): integra a rota de logout api na página de profile

docs/sprints/sprint-9.md, mkdocs.yml
- Adiciona o conteúdo da sprint 9 na documentação do projeto
=> mkdocs(docs): Adiciona a sprint 9

Makefile, api/api/management/commands/updatedb.py
- Criado comandos make para atualizar o banco de dados com as disciplinas.
- Foram corrigidos comentários no arquivo _updatedb.py_
=> DevOps(database): Cria comandos make para atualizar o banco de dados.

api/setup.cfg, api/users/backends/google.py, api/utils/sessions.py, api/utils/web_scraping.py
- Adiciona arquivos de configuração para o codecov
- Ignora linhas de códigos não-testáveis
=> tests(codecov): Adicionar arquivos de configuração

README.md
=> main(readme): update README.md

README.md
- Remove as embeds que não possuem função efetiva no README do GitHub.
=> main(readme): remove embeds

README.md
- Corrige o redirecionamento dos tópicos de acordo com o padrão do GitHub.
=> main(readme): fix repo redirects

api/api/tests/test_discipline_models.py
=> typo(tests): add pep8

docs/contributing.md, docs/executing.md, mkdocs.yml
- Foi criado duas páginas distintas para "Como executar" e "Como contribuir"
- Modificações no mkdocs.yml para adicionar as novas páginas
=> docs(mkdocs): Melhorias no Como contribuir e Como executar

docs/executing.md
- O campo "Equipe" foi removido da página de "**Como executar?**", pois não deveria estar ali.
=> docs(fix-page-como-executar): corrigindo texto da página como executar

web/app/schedules/info/page.tsx
Correção rápida de bug na visualização da página de informações
=> Frontend(infoPage): Padding error fixed

api/api/tests/test_get_schedules_api.py, api/api/tests/test_schedule_delete.py, api/api/tests/test_schedule_save.py, api/api/views/delete_schedule.py, api/api/views/save_schedule.py, api/api/views/schedules.py, api/utils/db_handler.py, api/utils/tests/test_database_handler.py, api/utils/tests/test_schedule_generator.py
- Foi criada uma verificação mais profunda, assim as grades poderam ser salvas com datas especiais
- Testes foram implementados pra verificar o salvamento de grades com datas especiais
=> fix(api): agora a api pode salvar grades com datas especias

README.md
- Coloca uma breve explicação de como realizar atualizações no banco de dados
=> docs(README): adiciona seção de atualização do banco de dados

.github/CODE_OF_CONDUCT.md
**Issue:**
close #161 
- Foi adicionado o código de conduta padrão para o projeto
=> docs(conduct): adiciona código de conduta padrão

web/app/page.tsx, web/app/schedules/layout.tsx, web/app/schedules/profile/page.tsx, web/app/utils/api/logout.ts
- Antes quando o usuário tinha grades salvas no cloud e fazia logout se o mesmo não recarregasse a página as mesmas ficavam no buffer, assim isso foi corrigido
=> fix(front): quando o usuário faz logout e tem grades no cloud essas não ficam mais no buffer

docs/sprints/sprint-12.md, docs/sprints/sprint-13.md, mkdocs.yml
- Adiciona o conteúdo das sprints 12 e 13 na documentação do projeto
=> mkdocs(docs): Adiciona as sprints 12 e 13

api/api/serializers.py, api/api/tests/test_search_api.py, api/api/views/views.py, api/utils/db_handler.py
**issue**
closes https://github.com/unb-mds/2023-2-Squad11/issues/159
O que foi feito?
- Adicionado filtro de pesquisa por nome de professor.
- A pesquisa por professor ocorre apenas se a pesquisa por nome da disciplina não retornar resultados.
- Apenas as turmas que o professor leciona são retornadas.
- Arquivos foram modificados para melhor leitura do código.
=> api(search): Filtra busca por nome do professor

web/app/schedules/home/components/GenerateScheduleButton.tsx, web/app/schedules/layout.tsx, web/app/utils/api/generateSchedule.ts
**Issue:**
close #180 
- Foi adicionado um _Modal_ para selecionar o período de preferência M | T | N
<div align="center">
</div>
- Um frame de loading foi adicionado antes de mostrar as novas grades geradas para melhor experiência do usuário caso a API esteja demorando mais para responder
<div align="center">
</div>
=> front(schedules): adiciona secção de preferência antes da geração de grades e frame de loading 

.github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Adiciona template para pull requests, esse mesmo que você está lendo.
Não há testes.
=> Adiciona template de pull request para contribuição.

web/app/contexts/ClassesToShowContext.tsx, web/app/schedules/home/page.tsx
closes #188 
* \[ ]   **Bug fix** (alteração que corrige um problema)
* \[x]   **New feature** (alteração que adiciona funcionalidade)
* \[ ]   **Breaking change** (correção ou funcionalidade que altera o comportamento de outras partes do sistema de maneira significativa)
* \[ ]   **Documentation update** (alteração na documentação)
[Screencast from 19-02-2024 17:00:59.webm](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/68292695/30ad85da-0894-4d22-96b0-0c2e9945f157)
[Screencast from 19-02-2024 17:04:23.webm](https://github.com/unb-mds/2023-2-SuaGradeUnB/assets/68292695/796c547d-afb8-4262-a987-29de69649e5e)
* \[x]   Meu código segue as diretrizes de contribuição deste projeto
* \[x]   Realizei uma revisão pessoal do meu código
* \[x]   Comentei meu código, especialmente em áreas de …
=> task(front/home): divide aulas por secção de disciplinas na página principal

api/requirements.txt
Atualiza versão do django de 4.2.11 para 5.1 para manter o projeto atualizado com as novas funcionalidades do Django. Além disso para corrige possíveis vulnerabilidades de SQL Injection.
**closes https://github.com/unb-mds/2023-2-SuaGradeUnB/security/dependabot/32**
* \[x]   **Bug fix** (alteração que corrige um problema)
* \[ ]   **New feature** (alteração que adiciona funcionalidade)
* \[ ]   **Breaking change** (correção ou funcionalidade que altera o comportamento de outras partes do sistema de maneira significativa)
* \[ ]   **Documentation update** (alteração na documentação)
* \[x]  Teste de unidade já existentes
* \[x]   Meu código segue as diretrizes de contribuição deste projeto
* \[ ]   Realizei uma revisão pessoal do meu código
* \[ ]   Comentei meu código, especialmente em …
=> Updates django version from 4.2.11 to 5.1

web/app/components/AsideSchedulePopUp/Form/InputForm.tsx, web/app/utils/api/searchDiscipline.ts
Altera o texto da caixa de input para que o usuário saiba que é possível pesquisar uma disciplina pelo nome de professor, como foi implementado em #167 . Além disso, altera a mensagem de erro retornada ao não encontrar nenhum resultado de busca para um texto mais amigável ao usuário do que o anterior.
* \[ ]   **Bug fix** (alteração que corrige um problema)
* \[ ]   **New feature** (alteração que adiciona funcionalidade)
* \[ ]   **Breaking change** (correção ou funcionalidade que altera o comportamento de outras partes do sistema de maneira significativa)
* \[ ]   **Documentation update** (alteração na documentação)
* \[x]   **UI/UX changes** (Alteração na interface de usuário)
* \[x]   Teste manual de interface
* \[x]   Meu código segue as diretrizes de contribuição deste projeto
* \[x] …
=> ui/ux: Changes input box and search error message to a more friendly message
